image: maven:3.8.4-jdk-11

cache:
  paths:
    - .m2/repository

maven-verify:
  stage: test
  services:
    - eclipse-mosquitto:1.6 # for mqtt client/server tests
  before_script:
    - sed -i 's/localhost/eclipse-mosquitto/g' wot-servient-integration-tests/src/test/resources/application.conf
  script:
    - 'mvn $MAVEN_CLI_OPTS verify sonar:sonar'
    - mv wot-servient-cli/target/wot-servient-*.zip .
  after_script:
    - '/bin/bash coverage-jacoco.sh'
  coverage: '/\d+.\d+ \% covered/'
  except:
    - master
    - /^\d+\.\d+/
  artifacts:
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"
    paths:
      - "wot-servient-*.zip"
